=== arnaudpourbaix/aTweaks/lib/schemas/generate.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/GenerateConfig",
  "definitions": {
      "GenerateConfig": {
          "type": "object",
          "properties": {
              "creaturesFolder": {
                  "type": "string"
              },
              "commonFunctionsFile": {
                  "type": "string"
              },
              "commonCreatureFile": {
                  "type": "string"
              },
              "immunitiesFile": {
                  "type": "string"
              },
              "bafConstants": {
                  "$ref": "#/definitions/BafConstants"
              },
              "tpaConstants": {
                  "$ref": "#/definitions/WeiduConstants"
              },
              "tokens": {
                  "$ref": "#/definitions/TokenConfig"
              },
              "constitutionAffectHitPoint": {
                  "type": "boolean"
              }
          },
          "required": [
              "creaturesFolder",
              "commonFunctionsFile",
              "commonCreatureFile",
              "immunitiesFile",
              "bafConstants",
              "tpaConstants",
              "tokens",
              "constitutionAffectHitPoint"
          ],
          "additionalProperties": false
      },
      "BafConstants": {
          "type": "object",
          "properties": {
              "initGlobal": {
                  "type": "string"
              },
              "restTimer": {
                  "type": "string"
              },
              "combatStarted": {
                  "type": "string"
              },
              "disableSpellcasting": {
                  "type": "string"
              },
              "roundTimer": {
                  "type": "string"
              },
              "allowMelee": {
                  "type": "string"
              },
              "fullHealSpellResource": {
                  "type": "string"
              },
              "monsterShoutId": {
                  "type": "number"
              },
              "summonerShoutId": {
                  "type": "number"
              },
              "trackingRange": {
                  "type": "number"
              }
          },
          "required": [
              "initGlobal",
              "restTimer",
              "combatStarted",
              "disableSpellcasting",
              "roundTimer",
              "allowMelee",
              "fullHealSpellResource",
              "monsterShoutId",
              "summonerShoutId",
              "trackingRange"
          ],
          "additionalProperties": false
      },
      "WeiduConstants": {
          "type": "object",
          "properties": {
              "genericScriptsToRemove": {
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
              }
          },
          "required": [
              "genericScriptsToRemove"
          ],
          "additionalProperties": false
      },
      "TokenConfig": {
          "type": "object",
          "properties": {
              "target": {
                  "type": "string"
              },
              "grabState": {
                  "type": "string"
              }
          },
          "required": [
              "target",
              "grabState"
          ],
          "additionalProperties": false
      }
  }
}

=== arnaudpourbaix/aTweaks/generate.json
{
  "creaturesFolder": "lib/pnp-monster/data",
  "commonCreatureFile": "lib/pnp-monster/common.tpa",
  "commonFunctionsFile": "lib/common/immune-trait.tpa",
  "immunitiesFile": "lib/pnp-monster/immunities.json",
  "constitutionAffectHitPoint": true,
  "bafConstants": {
    "allowMelee": "JA#MELEE",
    "combatStarted": "JA#COMBAT",
    "disableSpellcasting": "JA#DISABLE_SPELLCASTING",
    "initGlobal": "JA#INIT",
    "restTimer": "JA#REST",
    "roundTimer": "JA#ROUND",
    "fullHealSpellResource": "JA#HEAL",
    "monsterShoutId": 95,
    "summonerShoutId": 98,
    "trackingRange": 150
  },
  "tpaConstants": {
    "genericScriptsToRemove": [
      "SHOUT",
      "WTASIGHT",
      "WDASIGHT",
      "wtrunsgt",
      "DW2MP0GE",
      "DW2RC2MO"
    ]
  },
  "tokens": {
    "grabState": "{GrabState}",
    "target": "{Target}"
  }
}
